### ISSUE TITLE
Ability to delete a lab

### ISSUE THREAD

**Issue by aliirz** [codeforpakistan/Labtech-App#25]

**Comment by sohail0992** [comment]
All indicators and lab will be deleted as a result.

**Comment by sohail0992** [comment]
<img width="1380" alt="Screenshot 2021-08-30 at 1 17 07 PM" src="https://user-images.githubusercontent.com/23142014/131308613-e6333037-2e88-4a56-8beb-69022c1cdb45.png">
![Uploading Screenshot 2021-08-30 at 1.17.33 PM.png…]()

**Comment by aliirz** [comment]
👍
